// Generated by LiveScript 1.6.1
(function(){
  var macros, js;
  macros = require('../../lib/macros');
  macros.define('whn', function(test){
    var body, res$, i$, to$;
    res$ = [];
    for (i$ = 1, to$ = arguments.length; i$ < to$; ++i$) {
      res$.push(arguments[i$]);
    }
    body = res$;
    return macros.qq(['`', ['if', [',', test], [',@', body]]]);
  });
  js = macros.compile(['whn', true, ['console.log', 'example 1']]);
  console.log(js);
}).call(this);
