// Generated by LiveScript 1.6.1
(function(){
  var macros, exp1, exp2;
  macros = require('../../lib/macros');
  macros.define('make-pair', function(a, b){
    return macros.withScope(function(){
      var t;
      t = macros.gensym('p');
      return macros.qq(['`', ['do', ['var', [',', t], [',', a]], ['var', [',', t + "2"], [',', b]], [',', t], [',', t + "2"]]]);
    });
  });
  exp1 = macros.expand(['make-pair', 'x', 'y']);
  exp2 = macros.expand(['make-pair', 'x', 'y']);
  console.log(exp1[1][1] !== exp2[1][1]);
}).call(this);
