// Generated by LiveScript 1.6.1
(function(){
  var macros, js;
  macros = require('../../lib/macros');
  macros.define('aif', function(test, thenPart, elsePart){
    elsePart == null && (elsePart = null);
    return macros.withScope(function(it){
      it = macros.gensym('it');
      if (elsePart != null) {
        return macros.qq(['`', ['do', ['var', [',', it], [',', test]], ['if', [',', it], [',', thenPart], [',', elsePart]]]]);
      } else {
        return macros.qq(['`', ['do', ['var', [',', it], [',', test]], ['if', [',', it], [',', thenPart]]]]);
      }
    });
  });
  js = macros.compile(['aif', true, ['console.log', 'yes!'], ['console.log', 'no!']]);
  console.log(js);
}).call(this);
