// Generated by LiveScript 1.6.1
(function(){
  var macros, js;
  macros = require('../../lib/macros');
  macros.define('aif', function(test, thenPart, elsePart){
    elsePart == null && (elsePart = null);
    return macros.withScope(function(it){
      it = macros.gensym('it');
      if (elsePart != null) {
        return macros.qq(['`', ['do', ['var', [',', it], [',', test]], ['if', [',', it], [',', thenPart], [',', elsePart]]]]);
      } else {
        return macros.qq(['`', ['do', ['var', [',', it], [',', test]], ['if', [',', it], [',', thenPart]]]]);
      }
    });
  });
  macros.define('awhen', function(test){
    var body, res$, i$, to$;
    res$ = [];
    for (i$ = 1, to$ = arguments.length; i$ < to$; ++i$) {
      res$.push(arguments[i$]);
    }
    body = res$;
    return macros.qq(['`', ['aif', [',', test], ['do', [',@', body]]]]);
  });
  js = macros.compile(['awhen', true, ['console.log', 'done!']]);
  console.log(js);
}).call(this);
