// Generated by LiveScript 1.6.1
(function(){
  var macros, js;
  macros = require('../../lib/macros');
  macros.define('aif', function(test, thenPart, elsePart){
    elsePart == null && (elsePart = null);
    return macros.withScope(function(it){
      it = macros.gensym('it');
      if (elsePart != null) {
        return macros.qq(['`', ['do', ['var', [',', it], [',', test]], ['if', [',', it], [',', thenPart], [',', elsePart]]]]);
      } else {
        return macros.qq(['`', ['do', ['var', [',', it], [',', test]], ['if', [',', it], [',', thenPart]]]]);
      }
    });
  });
  macros.defineSyntax('aand', [[['aand'], true], [['aand', '@x'], '@x'], [['aand', '@x', '@rest...'], ['aif', '@x', ['aand', '@rest...'], '@x']]]);
  js = macros.compile(['aand', true, true, false]);
  console.log(js);
}).call(this);
