// Generated by LiveScript 1.6.1
(function(){
  var macros, js;
  macros = require('../../lib/macros');
  macros.define('swap', function(a, b){
    return macros.withScope(function(){
      var t;
      t = macros.gensym('t');
      return macros.qq(['`', ['do', ['var', [',', t], [',', a]], ['set', [',', a], [',', b]], ['set', [',', b], [',', t]]]]);
    });
  });
  js = macros.compile(['swap', 'x', 'y']);
  console.log(js);
}).call(this);
