// Generated by LiveScript 1.6.1
(function(){
  var macros, js;
  macros = require('../../lib/macros');
  macros.defineSyntax('if-let', [[['if-let', '@name', '@val', '@body...'], ['do', ['var', '@name', '@val'], ['if', '@name', '@body...']]]]);
  js = macros.compile(['if-let', 'x', true, ['console.log', '"set"']]);
  console.log(js);
}).call(this);
