// Generated by LiveScript 1.6.1
(function(){
  var macros, js;
  macros = require('../../lib/macros');
  macros.define('twice', function(expr){
    return ['do', expr, expr];
  });
  macros.define('announce', function(msg){
    return ['twice', ['console.log', msg]];
  });
  js = macros.compile(['announce', '"hello"']);
  console.log(js);
}).call(this);
