// Generated by LiveScript 1.6.1
(function(){
  var macros, exp;
  macros = require('../../lib/macros');
  macros.defineSyntax('kwote', [[['kwote', '@exp'], ['quote', '@exp']]]);
  exp = macros.expand(['kwote', ['foo', '.', 'bar']]);
  console.log(JSON.stringify(exp));
}).call(this);
