// Generated by LiveScript 1.6.1
(function(){
  var macros;
  macros = require('../../lib/macros');
  macros.defineSyntax('unless', [[['unless', '@cond', '@body...'], ['if', ['not', '@cond'], '@body...']]]);
  if (!false) {
    console.log('ran!');
  }
}).call(this);
