// Generated by LiveScript 1.6.1
var macroEnv, ls, fs, define, evalLS, defineLS, loadFile, isList, gensymCounter, gensym, matchPattern, substitute, defineSyntax, qq, expand;
macroEnv = {};
ls = require('./index');
fs = require('fs');
define = function(name, fn){
  return macroEnv[name] = fn;
};
evalLS = function(code){
  var js;
  js = ls.compile('(' + code + ')', {
    bare: true
  });
  js = js.replace(/^\/\/.*\n/, '').replace(/;\s*$/, '');
  return Function('macros', 'return (' + js + ')')(module.exports);
};
defineLS = function(name, code){
  return define(name, evalLS(code));
};
loadFile = function(filename){
  var Module, path, code, js, mod;
  Module = require('module');
  path = require('path');
  code = fs.readFileSync(filename, 'utf8');
  js = ls.compile(code, {
    bare: true
  });
  js = js.replace(/^\/\/.*\n/, '').replace(/;\s*$/, '');
  mod = new Module(filename, module);
  mod.filename = filename;
  mod.paths = Module._nodeModulePaths(path.dirname(filename));
  return mod._compile(js, filename);
};
isList = Array.isArray;
gensymCounter = 0;
gensym = function(prefix){
  prefix == null && (prefix = 'g$');
  gensymCounter = gensymCounter + 1;
  return prefix + gensymCounter;
};
matchPattern = function(pattern, expr, env){
  var n, restName, i$, to$, i;
  env == null && (env = {});
  if (typeof pattern === 'string') {
    if (/^@[\w-]+\.\.\.$/.test(pattern)) {
      env[pattern.slice(1, -3)] = expr;
      return true;
    } else if (/^@[\w-]+$/.test(pattern)) {
      env[pattern.slice(1)] = expr;
      return true;
    } else {
      return pattern === expr;
    }
  } else if (isList(pattern) && isList(expr)) {
    n = pattern.length;
    if (n > 0 && typeof pattern[n - 1] === 'string' && /^@[\w-]+\.\.\.$/.test(pattern[n - 1])) {
      restName = pattern[n - 1].slice(1, -3);
      if (expr.length < n - 1) {
        return false;
      }
      for (i$ = 0, to$ = n - 1; i$ < to$; ++i$) {
        i = i$;
        if (!matchPattern(pattern[i], expr[i], env)) {
          return false;
        }
      }
      env[restName] = expr.slice(n - 1);
      return true;
    } else if (expr.length === n) {
      for (i$ = 0, to$ = n - 1; i$ < to$; ++i$) {
        i = i$;
        if (!matchPattern(pattern[i], expr[i], env)) {
          return false;
        }
      }
      return true;
    } else {
      return false;
    }
  } else {
    return pattern === expr;
  }
};
substitute = function(template, env){
  var res, i$, len$, item, val;
  if (typeof template === 'string') {
    if (/^@[\w-]+$/.test(template)) {
      return env[template.slice(1)];
    } else {
      return template;
    }
  } else if (isList(template)) {
    res = [];
    for (i$ = 0, len$ = template.length; i$ < len$; ++i$) {
      item = template[i$];
      if (typeof item === 'string' && /^@[\w-]+\.\.\.$/.test(item)) {
        val = env[item.slice(1, -3)] || [];
        res = res.concat(val);
      } else {
        res.push(substitute(item, env));
      }
    }
    return res;
  } else {
    return template;
  }
};
defineSyntax = function(name, patterns){
  return define(name, function(){
    var expr, i$, ref$, len$, ref1$, pat, templ, env;
    expr = [name].concat(Array.prototype.slice.call(arguments));
    for (i$ = 0, len$ = (ref$ = patterns).length; i$ < len$; ++i$) {
      ref1$ = ref$[i$], pat = ref1$[0], templ = ref1$[1];
      env = {};
      if (matchPattern(pat, expr, env)) {
        return substitute(templ, env);
      }
    }
    throw new Error("no matching pattern for macro " + name);
  });
};
qq = function(x){
  var ref$, res, i$, len$, item, val;
  if (isList(x)) {
    if (x.length > 0) {
      if ((ref$ = x[0]) === 'unquote' || ref$ === ',') {
        return x[1];
      } else if ((ref$ = x[0]) === 'splice' || ref$ === ',@') {
        return {
          splice: true,
          value: qq(x[1])
        };
      } else if (x[0] === '`') {
        return qq(x[1]);
      } else {
        res = [];
        for (i$ = 0, len$ = x.length; i$ < len$; ++i$) {
          item = x[i$];
          val = qq(item);
          if (val != null && typeof val === 'object' && val.splice === true) {
            res = res.concat(val.value);
          } else {
            res.push(val);
          }
        }
        return res;
      }
    } else {
      return [];
    }
  } else {
    return x;
  }
};
expand = function(expr){
  var i$, to$, i;
  if (isList(expr)) {
    if (typeof expr[0] === 'string' && Object.hasOwnProperty.call(macroEnv, expr[0])) {
      return expand(macroEnv[expr[0]].apply(null, expr.slice(1)));
    } else {
      for (i$ = 0, to$ = expr.length; i$ < to$; ++i$) {
        i = i$;
        expr[i] = expand(expr[i]);
      }
      return expr;
    }
  } else {
    return expr;
  }
};
module.exports = {
  define: define,
  defineSyntax: defineSyntax,
  expand: expand,
  qq: qq,
  evalLS: evalLS,
  defineLS: defineLS,
  loadFile: loadFile,
  gensym: gensym
};

