// Generated by LiveScript 1.6.1
var macroEnv, ls, fs, define, evalLS, defineLS, loadFile, isList, scopeStack, gensymCounter, withScope, gensym, matchPattern, substitute, defineSyntax, qq, expand, toJs, compile, preprocess;
macroEnv = {};
ls = require('./index');
fs = require('fs');
define = function(name, fn){
  return macroEnv[name] = fn;
};
evalLS = function(code){
  var js;
  js = ls.compile('(' + code + ')', {
    bare: true
  });
  js = js.replace(/^\/\/.*\n/, '').replace(/;\s*$/, '');
  return Function('macros', 'return (' + js + ')')(module.exports);
};
defineLS = function(name, code){
  return define(name, evalLS(code));
};
loadFile = function(filename){
  var Module, path, code, js, mod;
  Module = require('module');
  path = require('path');
  code = fs.readFileSync(filename, 'utf8');
  js = ls.compile(code, {
    bare: true
  });
  js = js.replace(/^\/\/.*\n/, '').replace(/;\s*$/, '');
  mod = new Module(filename, module);
  mod.filename = filename;
  mod.paths = Module._nodeModulePaths(path.dirname(filename));
  return mod._compile(js, filename);
};
isList = Array.isArray;
scopeStack = [0];
gensymCounter = 0;
withScope = function(fn){
  var scopeId;
  scopeId = scopeStack.length;
  scopeStack.push(scopeId);
  try {
    return fn();
  } finally {
    scopeStack.pop();
  }
};
gensym = function(prefix){
  prefix == null && (prefix = 'g$');
  gensymCounter = gensymCounter + 1;
  return prefix + scopeStack.join('$') + '$' + gensymCounter;
};
matchPattern = function(pattern, expr, env){
  var n, restName, i$, to$, i;
  env == null && (env = {});
  if (typeof pattern === 'string') {
    if (/^@[\w-]+\.\.\.$/.test(pattern)) {
      env[pattern.slice(1, -3)] = expr;
      return true;
    } else if (/^@[\w-]+$/.test(pattern)) {
      env[pattern.slice(1)] = expr;
      return true;
    } else {
      return pattern === expr;
    }
  } else if (isList(pattern) && isList(expr)) {
    n = pattern.length;
    if (n > 0 && typeof pattern[n - 1] === 'string' && /^@[\w-]+\.\.\.$/.test(pattern[n - 1])) {
      restName = pattern[n - 1].slice(1, -3);
      if (expr.length < n - 1) {
        return false;
      }
      for (i$ = 0, to$ = n - 1; i$ < to$; ++i$) {
        i = i$;
        if (!matchPattern(pattern[i], expr[i], env)) {
          return false;
        }
      }
      env[restName] = expr.slice(n - 1);
      return true;
    } else if (expr.length === n) {
      for (i$ = 0, to$ = n - 1; i$ < to$; ++i$) {
        i = i$;
        if (!matchPattern(pattern[i], expr[i], env)) {
          return false;
        }
      }
      return true;
    } else {
      return false;
    }
  } else {
    return pattern === expr;
  }
};
substitute = function(template, env){
  var res, i$, len$, item, val;
  if (typeof template === 'string') {
    if (/^@[\w-]+$/.test(template)) {
      return env[template.slice(1)];
    } else {
      return template;
    }
  } else if (isList(template)) {
    res = [];
    for (i$ = 0, len$ = template.length; i$ < len$; ++i$) {
      item = template[i$];
      if (typeof item === 'string' && /^@[\w-]+\.\.\.$/.test(item)) {
        val = env[item.slice(1, -3)] || [];
        res = res.concat(val);
      } else {
        res.push(substitute(item, env));
      }
    }
    return res;
  } else {
    return template;
  }
};
defineSyntax = function(name, patterns){
  return define(name, function(){
    var expr, i$, ref$, len$, ref1$, pat, templ, env, patStr;
    expr = [name].concat(Array.prototype.slice.call(arguments));
    for (i$ = 0, len$ = (ref$ = patterns).length; i$ < len$; ++i$) {
      ref1$ = ref$[i$], pat = ref1$[0], templ = ref1$[1];
      env = {};
      if (matchPattern(pat, expr, env)) {
        return substitute(templ, env);
      }
    }
    patStr = patterns.map(function(p){
      return JSON.stringify(p[0]);
    }).join(', ');
    throw new Error("no matching pattern for macro " + name + "; tried " + patStr);
  });
};
qq = function(x){
  var ref$, res, i$, len$, item, val;
  if (isList(x)) {
    if (x.length > 0) {
      if ((ref$ = x[0]) === 'unquote' || ref$ === ',') {
        return x[1];
      } else if ((ref$ = x[0]) === 'splice' || ref$ === ',@') {
        return {
          splice: true,
          value: qq(x[1])
        };
      } else if (x[0] === '`') {
        return qq(x[1]);
      } else {
        res = [];
        for (i$ = 0, len$ = x.length; i$ < len$; ++i$) {
          item = x[i$];
          val = qq(item);
          if (val != null && typeof val === 'object' && val.splice === true) {
            res = res.concat(val.value);
          } else {
            res.push(val);
          }
        }
        return res;
      }
    } else {
      return [];
    }
  } else {
    return x;
  }
};
expand = function(expr){
  var i$, to$, i;
  if (isList(expr)) {
    if (typeof expr[0] === 'string' && Object.hasOwnProperty.call(macroEnv, expr[0])) {
      return withScope(function(){
        return expand(macroEnv[expr[0]].apply(null, expr.slice(1)));
      });
    } else {
      for (i$ = 0, to$ = expr.length; i$ < to$; ++i$) {
        i = i$;
        expr[i] = expand(expr[i]);
      }
      return expr;
    }
  } else {
    return expr;
  }
};
toJs = function(expr){
  var cond, cons, alt;
  if (typeof expr === 'string') {
    if (/^[A-Za-z_$][\w$.]*$/.test(expr)) {
      return expr;
    } else {
      return JSON.stringify(expr);
    }
  } else if (isList(expr)) {
    switch (expr[0]) {
    case 'if':
      cond = toJs(expr[1]);
      cons = toJs(expr[2]);
      if (expr.length > 3) {
        alt = toJs(expr[3]);
        return "if (" + cond + ") {" + cons + "} else {" + alt + "}";
      } else {
        return "if (" + cond + ") {" + cons + "}";
      }
    case 'not':
      return "!(" + toJs(expr[1]) + ")";
    case 'set':
      return toJs(expr[1]) + " = " + toJs(expr[2]);
    case 'var':
      return "var " + toJs(expr[1]) + " = " + toJs(expr[2]);
    case 'do':
      return expr.slice(1).map(function(e){
        return toJs(e);
      }).join('; ');
    default:
      return toJs(expr[0]) + "(" + expr.slice(1).map(function(e){
        return toJs(e);
      }).join(', ') + ")";
    }
  } else {
    return JSON.stringify(expr);
  }
};
compile = function(expr){
  return toJs(expand(expr));
};
preprocess = function(code){
  var out, i, j, open, close, start, depth, ch, expr, jsExpr;
  out = '';
  i = 0;
  while ((j = code.indexOf('macros.compile', i)) > -1) {
    out += code.slice(i, j);
    j += 'macros.compile'.length;
    while (/\s/.test(code[j])) {
      j++;
    }
    if (in$(code[j], '([')) {
      open = code[j];
      close = open === '(' ? ')' : ']';
      j++;
      start = j;
      depth = 1;
      while (depth > 0 && j < code.length) {
        ch = code[j];
        if (ch === open) {
          depth++;
        }
        if (ch === close) {
          depth--;
        }
        j++;
      }
      expr = code.slice(start, j - 1);
      jsExpr = eval('(' + expr + ')');
      out += compile(jsExpr);
      i = j;
    } else {
      out += 'macros.compile';
      i = j;
    }
  }
  out += code.slice(i);
  return out;
};
module.exports = {
  define: define,
  defineSyntax: defineSyntax,
  expand: expand,
  qq: qq,
  evalLS: evalLS,
  defineLS: defineLS,
  loadFile: loadFile,
  gensym: gensym,
  withScope: withScope,
  compile: compile,
  preprocess: preprocess
};
function in$(x, xs){
  var i = -1, l = xs.length >>> 0;
  while (++i < l) if (x === xs[i]) return true;
  return false;
}

